/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testclass_AndroidClass */

#ifndef _Included_com_example_testclass_AndroidClass
#define _Included_com_example_testclass_AndroidClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testclass_AndroidClass
 * Method:    AndroidClassGen
 * Signature: ([II)J
 */
JNIEXPORT jlong JNICALL Java_com_example_testclass_AndroidClass_AndroidClassGen
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_example_testclass_AndroidClass
 * Method:    AndroidClassFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_testclass_AndroidClass_AndroidClassFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_testclass_AndroidClass
 * Method:    calcMean
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_testclass_AndroidClass_calcMean
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_testclass_AndroidClass
 * Method:    calcSum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_testclass_AndroidClass_calcSum
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
